<html>
    <head>
        <title>Gerenciador de Certificados</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl('css/bootstrap.css'); ?>" />

    </head>
    <body>
        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="nav-collapse collapse">
                    <ul class="nav">
                        <li>
                            <a href="/clientes/index" onclick="">Clientes</a>
                        </li>
                        <li>
                            <a href="" onclick="">Cursos</a>
                        </li>
                        <li>
                            <a href="" onclick="">Usuários</a>
                        </li>
                        <li>
                            <a href="/turmas/index" onclick="">Turmas</a>
                        </li>
                        <li>
                            <a href="" onclick="">Certificados</a>
                        </li>
                    </ul>
                
                </div>
            </div>
        </div>
        <div id="content">

            <!-- menu  -->
            <div id="logged">
                <div id="menu">

                </div>
                <div id="user">
                    <?php
                    $auth = Zend_Auth::getInstance();
                    if ($auth->hasIdentity()):
                        ?>
                        <div class="formfield">

                            <b>Logado como: teste </b> 
                            <?php
                            /* $usuario = Zend_Auth::getInstance()->getIdentity();
                              echo $usuario->login;
                              if($usuario->tipo_usuario == 'A') {
                              echo " (ADMIN)";
                              } else {
                              echo " (COMUM)";
                              } */
                            ?>

                            <b>Último Login: </b>
                            <?php
                            /* $data_hora = $usuario->dt_ultimo_acesso;
                              $arrayDtUltimoAcesso = explode(" ", $data_hora);
                              echo $this->String($arrayDtUltimoAcesso[0])->reverseDate() . " " . $arrayDtUltimoAcesso[1];
                              //date_default_timezone_set('America/Sao_Paulo');
                              //echo date('Y-m-d h:i:s'); */
                            ?>
                            <!--<button type="button" id="sair" onclick="location.href='/index/sair'">Sair</button>-->

                            <a id="botao_sair" href="/index/sair">Sair</a>

                        </div>
                    <?php endif; ?>
                </div>
            </div>  
            <span style="color: red" id="divMsg">
                <?php if ($this->msg): ?>
                    <?php if (is_array($this->msg)): ?>

                        <?php echo implode("; ", $this->msg); ?>
                    <?php else: ?>
                        <?php echo $this->msg ?>
                    <?php endif; ?>
                <?php endif; ?>
            </span>
            <h1><?php echo $this->titlePage ?></h1>
            <?php echo $this->layout()->content; ?>
        </div>
    </body>
</html>
<script>
    //$(document).ready(function() {
    //Melhora aparência dos botões
    //$("#botao_sair").button(); 
    //});
</script>