<div class="container" style="margin-top: 50px">
    <form class="form-horizontal well" action="<?php echo $this->baseUrl('admin/usuario/form'); ?>" method="post">
        <fieldset>
            <legend>
                <?php echo $this->titulo; ?>
                <button id="novo_usuario" style="float: right; margin-top: 2px" class="btn btn-primary" type="button">Novo Usuário</button>
            </legend>

            <div class="form-actions" style="padding-left: 20px!important; margin-top: 0px">
                <div class="control-group">
                    <label class="control-label" for="nome">Nome</label>
                    <div class="controls">
                        <input class="input-xlarge" type="text" name="nome" id="nome" maxlength="18"/>
                    </div>
                </div>               
                <div class="control-group">
                    <label class="control-label" for="tipo_usuario">Tipo do usuário</label>
                    <div class="controls">
                        <select id="tipo_usuario" name="tipo_usuario">
                            <option selected value="">Selecione</option>
                            <option value="1">Administrador</option>
                            <option value="2">Cliente</option>
                            <option value="3">Aluno</option>
                        </select>
                    </div>
                </div>
                <div style="margin-bottom: -20px; margin-top: -20px" class="form-actions">
                    <input class="btn btn-primary" id="btBuscarUsuario" type="button" value="Buscar"/>
                </div>
            </div>
        </fieldset>
        <div id="div_usuario" >

        </div>
    </form>

</div>

</div>



<br />

<br />

<script>

    $(function(){
        //Melhora aparência dos botões
        //$( "input[type=submit], button" ).button();
       
        $('#novo_usuario').on("click", function(event){
            window.location = "<?php echo $this->baseUrl('admin/usuario/form'); ?>";
        });
       
        $('#div_usuario').load('<?php echo $this->baseUrl('admin/usuario/grid'); ?>');
        $('#btBuscarUsuario').click(function(){            
            nome = urlencodeGet($('#nome').val());
            tipo_usuario = $('#tipo_usuario').val();
            
            $('#div_usuario').load('<?php echo $this->baseUrl('admin/usuario/grid'); ?>'+'/nome/' + nome + '/tipo_usuario/' + tipo_usuario);
        });
        
    }); 
    
</script>