<div class="container" style="margin-top: 50px">
    <div id="div_mensagem"><?php echo ($this->msg != null) ? $this->msg[0] : "" ?></div>
    <form class="form-horizontal well" action="#" method="post">        
        <fieldset>
            <legend><?php echo $this->titulo; ?></legend>
            
            <!-- Botão novo alinhado a direita -->
            <input class="btn btn-primary" id="novo_aluno" type="button" value="Novo Aluno" style="float: right"/>
            <div style="clear: both;"></div>
            
            <!-- INICIO dos campos de busca -->
            <div class="form-actions" style="padding-left: 20px!important">
                <div class="control-group">
                    <label class="control-label" for="aluno-tx_nome_aluno">Nome</label>
                    <div class="controls">
                        <input class="input-xlarge" type="text" name="aluno[tx_nome_aluno]" id="aluno-tx_nome_aluno" maxlength="45"/>
                    </div>
                </div>
                
                <div class="control-group">
                    <label class="control-label" for="aluno-tx_cpf">CPF</label>
                    <div class="controls">
                        <input class="input-xlarge cpf" type="text" name="aluno[tx_cpf]" id="aluno-tx_cpf" maxlength="14"/>
                    </div>
                </div>
                                
                <input class="btn btn-primary" id="btBuscarAluno" type="button" value="Buscar"/>
            </div>
            <!-- FIM dos campos de busca -->            
        </fieldset>
        
        <div id="divResAluno"></div>
    </form>


</div>

<script>
    $(function(){                                             
        $('#divResAluno').load('<?php echo $this->baseUrl('admin/aluno/grid'); ?>');
        $('#btBuscarAluno').click(function(){            
            tx_nome_aluno = urlencodeGet($('#aluno-tx_nome_aluno').val());            
            tx_cpf = urlencodeGet($('#aluno-tx_cpf').val());                        
            
            $('#divResAluno').load('<?php echo $this->baseUrl('admin/aluno/grid'); ?>'+'/tx_nome_aluno/' + tx_nome_aluno + '/tx_cpf/' + tx_cpf);
        });
        
        //Carrega formulario de novo aluno com jquery
        $('#novo_aluno').click(function(){
            window.location = '/admin/aluno/form';
        });
    }); 
    
</script>