<div class="container" style="margin-top: 50px">
    <div id="div_mensagem"><?php echo ($this->msg != null) ? $this->msg[0] : "" ?></div>
    <form class="form-horizontal well" action="#" method="post">        
        <fieldset>
            <legend><?php echo $this->titulo; ?>
                <button id="novo_modelo" style="float: right; margin-top: 2px" class="btn btn-primary" type="button">Novo Modelo</button>
            </legend>                        
            
            <!-- INICIO dos campos de busca -->
            <div class="form-actions" style="padding-left: 20px!important">
                <div class="control-group">
                    <label class="control-label" for="certificado-tx_nome_modelo">Nome</label>
                    <div class="controls">
                        <input class="input-xlarge" type="text" name="certificado[tx_nome_modelo]" id="certificado-tx_nome_modelo" maxlength="30"/>
                    </div>
                </div>                                
                                
                <input class="btn btn-primary" id="btBuscarCertificado" type="button" value="Buscar"/>
            </div>
            <!-- FIM dos campos de busca -->            
        </fieldset>
        
        <div id="divResCertificado"></div>
    </form>


</div>

<script>
    $(function(){                                             
        //$('#divResAluno').load('<?php echo $this->baseUrl('admin/aluno/grid'); ?>');
        $('#btBuscarAluno').click(function(){            
            tx_nome_aluno = urlencodeGet($('#aluno-tx_nome_aluno').val());            
            tx_cpf = urlencodeGet($('#aluno-tx_cpf').val());                        
            
            $('#divResAluno').load('<?php echo $this->baseUrl('admin/aluno/grid'); ?>'+'/tx_nome_aluno/' + tx_nome_aluno + '/tx_cpf/' + tx_cpf);
        });
        
        //Carrega formulario de novo aluno com jquery
        $('#novo_modelo').click(function(){
            window.location = '/admin/certificado/form';
        });
    }); 
    
</script>