<div id="dialog-pesquisa-aluno" title="PESQUISA DE ALUNO" style="display:none; padding:0px;">            
    <!-- INICIO dos campos de busca -->
    <div class="form-actions" style="padding-left: 20px!important">                
        <div >
            <label style="display: inline-block; margin-right: 14px" for="selecionar-aluno-tx_nome_aluno">Nome</label>
            <input class="input-prepend required" style="margin-right: 25px" type="text" name="aluno[tx_nome_aluno]" id="selecionar-aluno-tx_nome_aluno" maxlength="45"/>
            <label style="display: inline-block; margin-right: 10px" for="selecionar-aluno-tx_cpf">CPF</label>
            <input class="input-prepend cpf" style="margin-right: 25px" type="text" name="aluno[tx_cpf]" id="selecionar-aluno-tx_cpf" maxlength="14"/>
        </div>
        
        <input class="btn btn-primary" id="btLocalizarAluno" onclick="localizarAluno()" type="button" value="Localizar"/>
    </div>
    <!-- FIM dos campos de busca --> 
    
    <fieldset style="min-height:425px">
        <div id='div-grid-pesquisar-aluno'></div>
    </fieldset>
</div>

<div id="avisoPesquisaAluno" title="ATENÇÃO">    
</div>            
            
<script>
    function configModalPesquisaAluno(){                
        /** configura a modal */
        $("#dialog-pesquisa-aluno").dialog({
            autoOpen: false,
            height: '600',
            width: '800',          
            modal: true,
            resizable: false,
            position: ['center','center'],
            closeOnEscape: true           
        });
    }        
    
    function closeModalPesquisaAluno(){			
        /** elimina a modal da memória */
        $("#dialog-pesquisa-aluno").dialog("close");
        /** fecha a modal ativando o click do botão de fechar */
        $('#dialog-pesquisa-aluno').prev('.ui-dialog-titlebar-close').click();               
    }

    function openModalPesquisaAluno(){
        configModalPesquisaAluno();
        $("#dialog-pesquisa-aluno").dialog("open");
    }
    function localizarAluno() {                
        tx_nome_aluno = urlencodeGet($.trim($('#selecionar-aluno-tx_nome_aluno').val()));
        tx_cpf = urlencodeGet($.trim($('#selecionar-aluno-tx_cpf').val()));
        
        if(tx_nome_aluno.length >= 3) {            
            $(this).attr('disabled',true);
            url = '<?php echo $this->baseUrl('/admin/aluno'); ?>/pesquisar-aluno/tx_nome_aluno/'+tx_nome_aluno+'/tx_cpf/'+tx_cpf;
            ShowMsgAguarde();
            $('#div-grid-pesquisar-aluno').load(url, function(data){
                $('#btLocalizarAluno').attr('disabled',false);
                CloseMsgAguarde();
            });
        } else {
            $('#avisoPesquisaAluno').html('Insira no mínimo 3 caracteres no Nome para realizar a busca!');                
            $('#avisoPesquisaAluno').dialog({
                modal: true,
                buttons: {
                    Ok: function() {
                        $(this).dialog("close");                            
                    }
                }
            });                                
            $('#avisoPesquisaAluno').dialog("open");
        }
    }
            
    $(document).ready(function(){            
        $('#avisoPesquisaAluno').dialog({
            autoOpen: false
        });                                      
        
        //coloca novamente a maskara de cpf
        $(".cpf").mask("999.999.999-99");
        
        //para todos os inputs da modal de selecionar o orientador, caso pressionado o enter deve ativar a pesquisa
        $('#dialog-pesquisa-aluno input').keypress(function(event){
            if(event.which == 13){				
                $('#btLocalizarAluno').click();
            }
        });               
    });
</script>