<?php
/** incia a captura do conteudo que sera renderizado como PDF */
ob_start();
?>
<style type="text/css">            
    .styleTD
    {
        font-size:10px; 
        border-bottom:1px solid #000000; 
        border-right:1px solid #000000; 
        padding:2px; 
        border-top:0px;
    }
    
    .styleTDTitulo
    {
        font-size:10px; 
        border-bottom:1px solid #000000; 
        border-right:1px solid #000000; 
        padding:2px; 
        border-top:1px solid #000000;
        background-color: #74b2e2;
    }         
</style>

<page backtop="7mm" backbottom="7mm" backleft="7mm" backright="7mm" style="font-size: 10pt">
    <page_header>
        <table style="border: solid 1px #000000; border-top:0px; border-left:0px; border-right:0px; border-bottom: 0px; padding: 5px; width: 100%; text-align: center;">
            <tr>           
                <td style="width: 100%; font-size: 16px;">
                    <b><?php echo strtoupper("SISTEMA GERANCIADOR DE CERTIFICADOS") ?></b>                                                          
                </td>            
            </tr>
        </table>
    </page_header>
    
    <page_footer>
        <table style="width: 100%; border: solid 1px black;">
            <tr>
                <td style="text-align: left;	width: 50%"><?php echo $this->utf8("Relatório de Certificados Emitidos")->decode(); ?></td>
                <td style="text-align: right;	width: 50%"><?php echo $this->utf8("Página")->decode(); ?> [[page_cu]] de [[page_nb]]</td>
            </tr>
        </table>
    </page_footer>

    <br/>

    <div style="text-align: center; width: 100%; font-weight: bold; font-size: 16px;">
        <?php echo $this->utf8("RELATÓRIO DE CERTIFICADOS EMITIDOS")->decode(); ?>
    </div>

    <br/><br/>   

    <?php 
  
        if(!empty($this->alunos)) {                    
            foreach($this->alunos as $aluno) {
    ?>
        <div style="text-align: justify; width: 100%; font-size: 12px;">
            <b>Nome do Aluno(a): </b><?=$aluno['tx_nome_aluno']?> - <b>CPF: </b><?=$aluno['tx_cpf']?>
            <br/>
            <b>Cargo: </b><?=$aluno['tx_cargo']?>            
        </div>
        <br/>
        <?php  
            $certificadosEmitidos = $aluno['certificados_emitidos'];
            $widthTreinamento = 'width: 170px';            
            $widthCargaHoraria = 'width: 70px';
            $widthInstrutor = 'width: 150px';
            $widthDataEmissao = 'width: 80px';
            $widthNumRegistro = 'width: 160px';
        ?>
            <table border='1' style='border:1px solid #000000; border-collapse:collapse; font-size:9px;'>
                <thead>
                    <tr style="font-size: 12;">
                        <th class="styleTDTitulo" colspan="5" style="text-align: center">
                            Certificados Emitidos
                        </th>                                   
                    </tr>
                    <tr style="font-size: 12;">
                        <th class="styleTDTitulo" style="text-align: center;<?=$widthTreinamento?>">
                            Treinamento
                        </th>
                        <th class="styleTDTitulo" style="text-align: center;<?=$widthCargaHoraria?>">
                            Carga Hor&aacute;ria
                        </th>
                        <th class="styleTDTitulo" style="text-align: center;<?=$widthInstrutor?>">
                            Instrutor
                        </th>
                        <th class="styleTDTitulo" style="text-align: center;<?=$widthDataEmissao?>">
                            Data Emiss&atilde;o
                        </th>
                        <th class="styleTDTitulo" style="text-align: center;<?=$widthNumRegistro?>">
                            Nr. Registro
                        </th>
                    </tr>
                </thead>
                <?php 
                    if(!empty($certificadosEmitidos)) {
                        //Para fazer linhas cor sim cornão
                        $exibe_cor = false;            
            
                        $somaCertificados = 0;
                        $somaCargaHoraria = 0;
                        foreach ($certificadosEmitidos as $certificado) {
                            //Para fazer linhas cor sim cornão
                            if ($exibe_cor) {
                                $cor = '#F0FFFF';
                                $exibe_cor = false;
                            } else {
                                $cor = '#FFFFFF';
                                $exibe_cor = true;
                            }
                            $somaCertificados++;
                            $somaCargaHoraria+=$certificado['nr_carga_horaria'];
                ?>
                        <tr>
                            <td style="text-align: left;background-color:<?php echo $cor ?>;<?=$widthTreinamento?>">
                                <?= $certificado['tx_nome_treinamento']; ?>
                            </td>
                            <td style="text-align: center;background-color:<?php echo $cor ?>;<?=$widthCargaHoraria?>">
                                <?= $certificado['nr_carga_horaria']; ?>
                            </td>
                            <td style="text-align: left;background-color:<?php echo $cor ?>;<?=$widthInstrutor?>">
                                <?= $certificado['tx_nome_instrutor']; ?>
                            </td>
                            <td style="text-align: center;background-color:<?php echo $cor ?>;<?=$widthDataEmissao?>">
                                <?= $this->String($certificado['dt_emissao_certificado'])->reverseDate(); ?>
                            </td>
                            <td style="text-align: left;background-color:<?php echo $cor ?>;<?=$widthNumRegistro?>">
                                <?= $certificado['nr_registro_certificado']; ?>
                            </td>
                        </tr>
                <?php 
                        }
                ?>
                        <tr>
                            <td style="text-align: right;background-color:#CDCDB4">
                                <b>TOTAL</b>
                            </td>
                            <td style="text-align: center;background-color:#CDCDB4">
                                <b><?=$somaCargaHoraria?></b>
                            </td>
                            <td colspan="2" style="text-align: center;background-color:#CDCDB4">
                                <b>&nbsp;</b>
                            </td>
                            <td style="text-align: center;background-color:#CDCDB4">
                                <b><?=$somaCertificados?></b>
                            </td>
                        </tr>
                <?php        
                    } else {
                ?>
                    <tr>
                        <td colspan="5" style="text-align: center;width: 680px" >
                            Nenhum Certificado foi Emitido para esse Aluno.
                        </td>
                    </tr>
                <?php } ?>                   
             </table>
             <br/>
    <?php 
            }
        } else { 
    ?>
        <div style="text-align: justify; width: 100%; font-size: 14px;">
            <?php echo $this->utf8("Nenhum Aluno foi encontrado com os filtro informado, tente outros valores.")->decode(); ?>
        </div>
    <?php } ?>
</page>

<?php
/** finaliza a captura do conteudo */

$content = ob_get_clean();
/** renderiza o PDF */
$orientation = 'P'; //L = PAISAGEM
//P = Porta Retrato
/** renderiza o PDF */
$this->pdf($content, 'RELATORIO_CERTIFICADOS.pdf', null, $orientation);
?>
