<?php
/** incia a captura do conteudo que sera renderizado como PDF */
ob_start();
?>
<style type="text/css">            
    .styleTD
    {
        font-size:10px; 
        border-bottom:1px solid #000000; 
        border-right:1px solid #000000; 
        padding:2px; 
        border-top:0px;
    }
    
    .styleTDTitulo
    {
        font-size:10px; 
        border-bottom:1px solid #000000; 
        border-right:1px solid #000000; 
        padding:2px; 
        border-top:1px solid #000000;
        background-color: #74b2e2;
    }         
</style>

<page backtop="7mm" backbottom="7mm" backleft="7mm" backright="7mm" style="font-size: 10pt">
    <page_header>
        <table style="border: solid 1px #000000; border-top:0px; border-left:0px; border-right:0px; border-bottom: 0px; padding: 5px; width: 100%; text-align: center;">
            <tr>           
                <td style="width: 100%; font-size: 16px;">
                    <b><?php echo strtoupper("SISTEMA GERANCIADOR DE CERTIFICADOS") ?></b>                                                          
                </td>            
            </tr>
        </table>
    </page_header>
    
    <page_footer>
        <table style="width: 100%; border: solid 1px black;">
            <tr>
                <td style="text-align: left;	width: 50%"><?php echo $this->utf8("Relatório de Treinametos")->decode(); ?></td>
                <td style="text-align: right;	width: 50%"><?php echo $this->utf8("Página")->decode(); ?> [[page_cu]] de [[page_nb]]</td>
            </tr>
        </table>
    </page_footer>

    <br/>

    <div style="text-align: center; width: 100%; font-weight: bold; font-size: 16px;">
        <?php echo $this->utf8("RELATÓRIO DE TREINAMENTOS")->decode(); ?>
    </div>

    <br/><br/>   

    <?php 
  
        if(!empty($this->turmas)) {                    
            foreach($this->turmas as $turma) {
    ?>
        <div style="text-align: justify; width: 100%; font-size: 12px;">
            <b>Nome do Treinamento: </b><?=$turma['tx_nome_treinamento']?> - <b>Carga Hor&aacute;ria: </b><?=$turma['nr_carga_horaria']?> Hora(s) - <b>Per&iacute;odo: </b>
            <?php echo $this->String($turma['dt_inicio_treinamento'])->reverseDate();?> &agrave; <?php echo $this->String($turma['dt_termino_treinamento'])->reverseDate();?>
            <br/>
            <b>Instrutor: </b><?=$turma['tx_nome_instrutor']?>
            <br/>
            <b>Descri&ccedil;&atilde;o: </b><?=$turma['tx_descricao']?>
        </div>
        <br/>
        <?php  
            $alunos = $turma['alunos'];
            $widthCliente = 'width: 350px';
            $widthAluno = 'width: 350px';
        ?>
            <table border='1' style='border:1px solid #000000; border-collapse:collapse; font-size:9px;'>
                <thead>
                    <tr style="font-size: 12;">
                        <th class="styleTDTitulo" colspan="2" style="text-align: center">
                            Alunos Participantes
                        </th>                                   
                    </tr>
                    <tr style="font-size: 12;">
                        <th class="styleTDTitulo" style="text-align: center;<?=$widthCliente?>">
                            Cliente
                        </th>
                        <th class="styleTDTitulo" style="text-align: center;<?=$widthAluno?>">
                            Aluno
                        </th>            
                    </tr>
                </thead>
                <?php 
                    if(!empty($alunos)) {
                        //Para fazer linhas cor sim cornão
                        $exibe_cor = false;            
            
                        $somaAlunos = 0;
                        foreach ($alunos as $aluno) {
                            //Para fazer linhas cor sim cornão
                            if ($exibe_cor) {
                                $cor = '#F0FFFF';
                                $exibe_cor = false;
                            } else {
                                $cor = '#FFFFFF';
                                $exibe_cor = true;
                            }
                            $somaAlunos++;
                ?>
                        <tr>
                            <td style="text-align: left;background-color:<?php echo $cor ?>">
                                <?= $aluno['tx_cliente']; ?>
                            </td>
                            <td style="text-align: left;background-color:<?php echo $cor ?>">
                                <?= $aluno['tx_nome_aluno']; ?>
                            </td>
                        </tr>
                <?php 
                        }
                ?>
                        <tr>
                            <td style="text-align: right;background-color:#CDCDB4">
                                <b>TOTAL</b>
                            </td>
                    
                            <td  style="text-align: center;background-color:#CDCDB4">
                                <b><?=$somaAlunos?></b>
                            </td>
                        </tr>
                <?php        
                    } else {
                ?>
                    <tr>
                        <td colspan="2" style="text-align: center">
                            Nenhum Aluno Matriculado.
                        </td>
                    </tr>
                <?php } ?>                   
             </table>   
    <?php 
            }
        } else { 
    ?>
        <div style="text-align: justify; width: 100%; font-size: 14px;">
            <?php echo $this->utf8("Nenhum Treinamento foi encontrado com os filtros informados, tente outros valores.")->decode(); ?>
        </div>
    <?php } ?>
</page>

<?php
/** finaliza a captura do conteudo */

$content = ob_get_clean();
/** renderiza o PDF */
$orientation = 'P'; //L = PAISAGEM
//P = Porta Retrato
/** renderiza o PDF */
$this->pdf($content, 'RELATORIO_TREINAMENTOS.pdf', null, $orientation);
?>
