<div class="container" style="margin-top: 50px">
    <form id="form_turma" class="form-horizontal well" action="<?php echo $this->baseUrl('/admin/turma/salvar') ?>/id/<?php echo $this->turma['id_turma'] ?>" method="post">

        <fieldset>
            <legend><?php echo $this->titulo; ?></legend>
            <input type="hidden" class="required" name="id_treinamento" id="id_treinamento"/>

            <fieldset style="margin-top: -40px">
                <h5 style="margin-top: 40px">Dados do Treinamento</h5>
                <hr style="margin-top: -10px">
                <div align="right" class="control-group">
                    <input class="btn btn-primary" id="btModalTreinamento" type="button" value="Buscar Treinamento"/>
                    <input class="btn" id="btLimparTreinamento" type="button" value="Limpar"/>
                </div>

                <div style="margin-top: -50px" class="control-group">
                    <label class="control-label" for="">Nome</label>
                    <div class="controls">
                        <span class="help-block label" id="dados-treinamento_tx_nome_treinamento"></span>
                    </div>
                </div>

                <div class="control-group">
                    <label class="control-label" for="">Carga Horária</label>
                    <div class="controls">
                        <span class="help-block label" id="dados-treinamento_nr_carga_horaria"></span>
                    </div>
                </div>
            </fieldset>         

            <div style="margin-left: 89px">
                <label style="display: inline-block; margin-right: 16px" for="dt_inicio_treinamento">Data Início</label>
                <input class="input-prepend required input-medium" style="margin-right: 25px" type="text" name="dt_inicio_treinamento" id="dt_inicio_treinamento" value=""/>
                <label style="display: inline-block; margin-right: 16px" for="dt_termino_treinamento">Data Término</label>
                <input class="input-prepend input-medium required" style="margin-right: 25px" type="text"  name="dt_termino_treinamento" id="dt_termino_treinamento" value=""/>
            </div>

            <div class="form-actions">
                <input class="btn btn-primary" id="btEnviar" type="submit" value="Salvar"/>
                <input class="btn" id="btVoltar" onclick="window.back()" type="button" value="Voltar"/>
            </div>
        </fieldset>
    </form>
</div>

<?php
echo $this->render('partials/modal-pesquisa-treinamento.phtml');
?>

<div id="mensagemTurma">
    <p style="color: #000 !important"></p>
</div>

<script>
    var dataForm = <?php echo Zend_Json::encode($this->turma); ?>;
    var autoCompleteTreinamentos = <?php echo Zend_Json::encode($this->autoCompleteTreinamentos); ?>;
    
    function callBackPesquisarTreinamento(dataTreinamento) {
        $('#id_treinamento').val(dataTreinamento.id_treinamento);
        $('#dados-treinamento_tx_nome_treinamento').html(dataTreinamento.tx_nome_treinamento);
        $('#dados-treinamento_nr_carga_horaria').html(dataTreinamento.nr_carga_horaria + ' horas');            
    }
    
    $(function(){
        
        $('#dt_inicio_treinamento').datepicker({dateFormat: 'dd/mm/yy'});
        $('#dt_termino_treinamento').datepicker({dateFormat: 'dd/mm/yy'});
    
        $('#form_turma').populate(dataForm);
        
        $('#btModalTreinamento').click(function() {
            openModalPesquisaTreinamento();
        });
        
<?php if (!empty($this->turma)) { ?>
            callBackPesquisarTreinamento(<?php echo Zend_Json::encode($this->turma) ?>);
<?php } ?>
        
        //        $('#nome_treinamento').autocomplete({
        //            minLength: 0,
        //            source: autoCompleteTreinamentos,
        //            select: function(event, ui){
        //                if(ui.item){
        //                    $('#id_treinamento').val(ui.item.id);
        //                }
        //            },
        //            change: function(event, ui){
        //                if(!ui.item){
        //                    $(this).val('');
        //                    $('#id_treinamento').val('');
        //                }
        //            }
        //        });
        
        $('#form_turma').validate({
            submitHandler: function(form) {
                if($('#id_treinamento').val() == '') {
                    $('#mensagemTurma').html("Selecione o Treinamento para esta Turma.");                            
                    $("#mensagemTurma").dialog({
                        modal: true,
                        buttons: {
                            Ok: function() {
                                $(this).dialog("close");                                        
                            }
                        }
                    });
                    $('#mensagemAluno').dialog("open");
                } else {
                    jQuery(form).ajaxSubmit({
                        dataType:  'json', 
                        success: function(r){
                            if(r.tipo == 'sucesso'){                    
                                $('#mensagemTurma p').html(r.msg);
                                $( "#mensagemTurma" ).dialog({
                                    modal: true,
                                    buttons: {
                                        Ok: function() {
                                            $(this).dialog("close");
                                            window.location = r.url;
                                        }
                                    }
                                });
                            } else {
                                $('#mensagemTurma p').html(r.msg);
                                $('#mensagemTurma').dialog({
                                    buttons: {
                                        Ok: function() {
                                            $( this ).dialog( "close" );
                                        }
                                    }
                                });
                            }
                        } 
                    });
                } 
            }
        });
    });
        
</script>