<table class="table table-bordered table-striped table-hover">
    <tr>
        <th>Treinamento</th>
        <th>Data de início</th>
        <th>Data de término</th>
        <th>Ações</th>
    </tr>

    <tr class="alt" >
        <?php foreach ($this->paginator as $k => $turmas): ?>
        <tr class="<?php echo ($k % 2 == 0) ? 'alt' : '' ?>">
            <td><?php echo $turmas['tx_nome_treinamento'] ?></td>
            <td><?php echo $turmas['dt_inicio_treinamento'] ?></td>
            <td><?php echo $turmas['dt_termino_treinamento'] ?></td>
            <td>
                <a class="linkEditar" href="<?php echo $this->baseUrl('/admin/turma/form') ?>/id/<?php echo $turmas['id_turma'] ?>">
                    <img src="/img/edit-icon.gif" title="Editar registro" />
                </a>
                <a class="btExcluir" href="<?php echo $this->baseUrl('/admin/turma/excluir') ?>/id/<?php echo $turmas['id_turma'] ?>">
                    <img src="/img/delete-icon.gif" title="Excluir Registro" />
                </a>
            </td>
        </tr>    
    <?php endforeach; ?>

</table>

<?php echo $this->paginationControl($this->paginator, 'Sliding', 'my_pagination_control.phtml'); ?>

<div id="dcTurma">
    <span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>Deseja realmente excluir essa turma?
</div>

<div id="turmaErro">
    Erro    
</div>

<div id="turmaSucesso">
    Sucesso    
</div>


<script>
    
    var url = "";
    $(function(){
        
        $( "#turmaSucesso" ).dialog({
            modal: true,
            autoOpen: false
        });
        
        $( "#turmaErro" ).dialog({
            modal: true,
            autoOpen: false
        });
                
        $("#dcTurma").dialog({
            resizable: false,
            height:250,
            width:500,
            modal: true,
            title: "Aviso",
            autoOpen: false,
                
            buttons: {
                "Ok": function() {
                    $.get(url, null, function(retorno){
                        if(retorno.tipo == 'sucesso'){
                            $('#turmaSucesso').html(retorno.msg);
                            
                            $('#turmaSucesso').dialog({
                                buttons: {
                                    Ok: function() {
                                        $( this ).dialog( "close" );
                                    }
                                }
                            });
                            $('#turmaSucesso').dialog("open");    
                            $('#div_turma').load('<?php echo $this->baseUrl('admin/turma/grid'); ?>');                                
                        } else {
                            $('#turmaErro').html(retorno.msg);                            
                            $('#turmaErro').dialog({
                                buttons: {
                                    Ok: function() {
                                        $( this ).dialog( "close" );
                                    }
                                }
                            });
                            $('#turmaErro').dialog("open");
                            $('#div_turma').load('<?php echo $this->baseUrl('admin/turma/grid'); ?>');
                        }                    
                    }, 'json');
                    $( this ).dialog("close");
                    
                },
                Cancel: function() {
                    $('#div_turma').load('/turma/grid/');
                    $( this ).dialog( "close" );
                    
                }
    
            }
                
        });
                
        $('.pagination a').click(function(){
           
            var href = $(this).attr('href');
            $('#div_turma').load(href);
            return false;
        });
        
        $('.btExcluir').click(function(){
            
            url = $(this).attr('href');
            $("#dcTurma").dialog("open");
            
            return false;
        });
        
    });
    
</script>