<div class="container" style="margin-top: 50px">
    <form class="form-horizontal well" action="" method="post">
        <fieldset>
            <legend><?php echo $this->titulo; ?></legend>
            <div class="control-group">
                <label class="control-label" for="login">Login</label>
                <div class="controls">
                    <input class="input-xlarge" type="text" name="tx_login" id="tx_login"/>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="senha">Senha</label>
                <div class="controls">
                    <input class="input-xlarge" type="password" name="tx_senha" id="tx_senha"/>
                </div>
            </div>
            <div class="form-actions">
                <input class="btn btn-primary" id="btEnviar" type="submit" value="Entrar"/>
            </div>
        </fieldset>
    </form>
</div>