<div class="container" style="margin-top: 50px">
    <div id="div_mensagem"><?php echo ($this->msg != null) ? $this->msg[0] : "" ?></div>
    <form id="form_aluno" class="form-horizontal well" action="<?php echo $this->baseUrl('/admin/certificado/salvar'); ?>" method="post">
        <fieldset>
            <legend><?php echo $this->titulo; ?></legend>
            <input type="hidden" name="certificado[id_certificado]" id="certificado-id_certificado"/>
            <input type="hidden" class="required" name="aluno[id_cliente]" id="aluno-id_cliente"/>
                                                                          
            
            <fieldset>
                <legend>Dados do Aluno</legend>                
                <div class="control-group">
                    <label class="control-label" for="aluno-tx_nome_aluno">Nome</label>
                    <div class="controls">
                        <input class="input-xlarge required" type="text" name="aluno[tx_nome_aluno]" id="aluno-tx_nome_aluno" maxlength="45"/>
                    </div>
                </div> 
                
                <div class="control-group">
                    <label class="control-label" for="aluno-tx_rg">RG</label>
                    <div class="controls">
                        <input class="input-xlarge" type="text" name="aluno[tx_rg]" id="aluno-tx_rg" maxlength="9"/>
                    </div>
                </div>
            
                <div class="control-group">
                    <label class="control-label" for="aluno-tx_cpf">CPF</label>
                    <div class="controls">
                        <input class="input-xlarge required cpf validarCPF" type="text" name="aluno[tx_cpf]" id="aluno-tx_cpf" maxlength="14"/>
                    </div>
                </div>
            
                <div class="control-group">
                    <label class="control-label" for="aluno-tx_cargo">Profissão</label>
                    <div class="controls">
                        <input class="input-xlarge" type="text" name="aluno[tx_cargo]" id="aluno-tx_cargo" maxlength="45"/>
                    </div>
                </div>                                               
            </fieldset>             
                                        
            
            <div class="form-actions">
                <input class="btn btn-primary" id="btEnviar" type="submit" value="Salvar"/>
                <input class="btn" id="btVoltar" onclick="window.back()" type="button" value="Voltar"/>
            </div>
        </fieldset>
    </form>
</div>

<?php    
    echo $this->render('partials/modal-pesquisa-cliente.phtml');
?>

<div id="mensagemAluno">    
</div>

<script>    
    var dataForm = <?php echo Zend_Json::encode(array('aluno' => $this->aluno)); ?>;      
    
    function callBackPesquisarCliente(dataCliente) {        
        $('#aluno-id_cliente').val(dataCliente.id_cliente);
        if(dataCliente.tx_tipo_cliente == 'F') {
            $('#dados-cliente_tx_tipo').html('Pessoa Física');
            $('#dados-cliente_tx_nome_razao_social').html(dataCliente.tx_nome);
            $('#dados-cliente_tx_cpf_cnpj').html(dataCliente.tx_cpf);            
        } else {
            $('#dados-cliente_tx_tipo').html('Pessoa Jurídica');
            $('#dados-cliente_tx_nome_razao_social').html(dataCliente.tx_razao_social);
            $('#dados-cliente_tx_cpf_cnpj').html(dataCliente.tx_cnpj);
        }
    }
    
    $(function(){   
        $('#form_aluno').populate(dataForm);
                
        $('#btLimparCliente').click(function() {
            $('.help-block').html('');
        });
        
        $('#btModalCliente').click(function() {
            openModalPesquisaCliente();
        });
        
        $('#mensagemCliente').dialog({
            autoOpen: false
        });                  
        
        <?php if(!empty($this->cliente)) { ?>
            callBackPesquisarCliente(<?php echo Zend_Json::encode($this->cliente) ?>);
        <?php } ?>
            
        $('#form_aluno').validate({
            submitHandler: function(form) {
                if($('#aluno-id_cliente').val() == '') {
                    $('#mensagemAluno').html("Selecione o Cliente responsável por esse Aluno");                            
                    $("#mensagemAluno").dialog({
                        modal: true,
                        buttons: {
                            Ok: function() {
                                $(this).dialog("close");                                        
                            }
                        }
                    });
                    $('#mensagemAluno').dialog("open");
                } else {
                    jQuery(form).ajaxSubmit({
                        dataType:  'json', 
                        success: function(r){
                            if(r.tipo == 'sucesso'){
                                //$('#div_mensagem').html(r.msg);
                                window.location = r.url;
                            } else {
                                $('#mensagemAluno').html(r.msg);                            
                                $("#mensagemAluno").dialog({
                                    modal: true,
                                    buttons: {
                                        Ok: function() {
                                            $(this).dialog("close");                                        
                                        }
                                    }
                                });
                                $('#mensagemAluno').dialog("open");                            
                            }
                        } 
                    });
                }
            } 
        });
    });
        
</script>