<div class="container" style="margin-top: 50px">
    <div id="div_mensagem"><?php echo ($this->msg != null) ? $this->msg[0] : "" ?></div>
    <form id="form_certificado" enctype="multipart/form-data" class="form-horizontal well" action="<?php echo $this->baseUrl('/admin/certificado/salvar'); ?>" method="post">
        <fieldset>
            <legend><?php echo $this->titulo; ?></legend>
            <input type="hidden" name="certificado[id_certificado]" id="certificado-id_certificado"/>
            <input type="hidden" name="certificado[tx_url_logotipo_cabecalho_esquerda]" id="certificado-tx_url_logotipo_cabecalho_esquerda"/>
            <input type="hidden" name="certificado[tx_url_logotipo_cabecalho_centro]" id="certificado-tx_url_logotipo_cabecalho_centro"/>
            <input type="hidden" name="certificado[tx_url_logotipo_cabecalho_direita]" id="certificado-tx_url_logotipo_cabecalho_direita"/>
            <input type="hidden" name="certificado[tx_url_logotipo_rodape_esquerda]" id="certificado-tx_url_logotipo_rodape_esquerda"/>
            <input type="hidden" name="certificado[tx_url_logotipo_rodape_direita]" id="certificado-tx_url_logotipo_rodape_direita"/>
            
            <fieldset>
                <legend>Dados do Modelo</legend>                
                <div class="control-group">
                    <label class="control-label" for="certificado-tx_nome_modelo">Nome do Modelo</label>
                    <div class="controls">
                        <input class="input-xlarge required" type="text" name="certificado[tx_nome_modelo]" id="certificado-tx_nome_modelo" maxlength="30"/>
                    </div>
                </div>                                                                                
            </fieldset>             
                                        
            <fieldset>
                <legend>Dados Cabeçalho</legend>                
                <div class="control-group">
                    <label class="control-label" for="certificado-tx_titulo">Título</label>
                    <div class="controls">
                        <input class="input-xlarge required" type="text" name="certificado[tx_titulo]" id="certificado-tx_titulo" maxlength="45"/>
                    </div>
                </div>
                
                <div class="control-group">
                    <label class="control-label" for="fileUploadLogoTopoEsquerda">Logo Canto Esquerdo</label>
                    <div class="controls">                        
                        <input class="input-xlarge" type="file" name="fileUploadLogoTopoEsquerda" id="fileUploadLogoTopoEsquerda"/>
                        <div id="preview_logo_topo_esquerda" type="button" style="width: 150px;text-align: center;padding-top:10px">
                            
                        </div>
                    </div>
                    
                </div>
            </fieldset>
            
            <div class="form-actions">
                <input class="btn btn-primary" id="btEnviar" type="submit" value="Salvar"/>
                <input class="btn" id="btVoltar" onclick="window.back()" type="button" value="Voltar"/>
            </div>
        </fieldset>
    </form>
</div>

<?php    
    echo $this->render('partials/modal-pesquisa-cliente.phtml');
?>

<div id="mensagemCertificado">    
</div>

<script>    
    var dataForm = <?php echo Zend_Json::encode(array('aluno' => $this->aluno)); ?>;      
    
    function callBackPesquisarCliente(dataCliente) {        
        $('#aluno-id_cliente').val(dataCliente.id_cliente);
        if(dataCliente.tx_tipo_cliente == 'F') {
            $('#dados-cliente_tx_tipo').html('Pessoa Física');
            $('#dados-cliente_tx_nome_razao_social').html(dataCliente.tx_nome);
            $('#dados-cliente_tx_cpf_cnpj').html(dataCliente.tx_cpf);            
        } else {
            $('#dados-cliente_tx_tipo').html('Pessoa Jurídica');
            $('#dados-cliente_tx_nome_razao_social').html(dataCliente.tx_razao_social);
            $('#dados-cliente_tx_cpf_cnpj').html(dataCliente.tx_cnpj);
        }
    }
    
    $(function(){   
        $('#form_aluno').populate(dataForm);
                
        $('#btLimparCliente').click(function() {
            $('.help-block').html('');
        });
        
        $('#btModalCliente').click(function() {
            openModalPesquisaCliente();
        });
        
        $('#mensagemCliente').dialog({
            autoOpen: false
        });                  
        
        $('#fileUploadLogoTopoEsquerda').change(function(){
            url_original = $('#form_certificado').attr('action');
            ShowMsgAguarde();
            $('#form_certificado').ajaxSubmit({
                url: '<?php echo $this->baseUrl('/admin/certificado/upload-logo-topo'); ?>',
                success: function(data){                
                    $('#form_certificado').attr('action', url_original);
                    $('#form_certificado').removeAttr('target');                    
                    $('#mensagemCertificado').html(data.msg);                            
                    $('#mensagemCertificado').dialog({
                        modal: true,
                        title: "ATENÇÃO",
                        buttons: {
                            "Ok": function() {
                                $( this ).dialog( "close" );
                            }
                        }
                    });
                    $('#mensagemCertificado').dialog("open");
                    
                    if(data.tipo == 'sucesso') {
                        $('#certificado-tx_url_logotipo_cabecalho_esquerda').val(data.urlArquivo);
                        $('#preview_logo_topo_esquerda').html(data.htmlImagem);
                    } else {
                        $('#fileUploadLogoTopoEsquerda').val('');
                    }
                }
            });
            CloseMsgAguarde();
        });
            
        $('#form_aluno').validate({
            submitHandler: function(form) {
                if($('#aluno-id_cliente').val() == '') {
                    $('#mensagemAluno').html("Selecione o Cliente responsável por esse Aluno");                            
                    $("#mensagemAluno").dialog({
                        modal: true,
                        buttons: {
                            Ok: function() {
                                $(this).dialog("close");                                        
                            }
                        }
                    });
                    $('#mensagemAluno').dialog("open");
                } else {
                    jQuery(form).ajaxSubmit({
                        dataType:  'json', 
                        success: function(r){
                            if(r.tipo == 'sucesso'){
                                //$('#div_mensagem').html(r.msg);
                                window.location = r.url;
                            } else {
                                $('#mensagemAluno').html(r.msg);                            
                                $("#mensagemAluno").dialog({
                                    modal: true,
                                    buttons: {
                                        Ok: function() {
                                            $(this).dialog("close");                                        
                                        }
                                    }
                                });
                                $('#mensagemAluno').dialog("open");                            
                            }
                        } 
                    });
                }
            } 
        });
    });
        
</script>