<html>
    <head>
        <title>Gerenciador de Certificados - Modulo Admin</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl('css/bootstrap.css'); ?>" />
        <link type="text/css" href="<?php echo $this->baseUrl('/css/cupertino/jquery-ui-1.10.1.custom.css'); ?>" rel="stylesheet" />
        <script type="text/javascript"  src="<?php echo $this->baseUrl('/js/jquery-1.9.1.js'); ?>"></script>
        <script type="text/javascript"  src="<?php echo $this->baseUrl('/js/jquery-ui-1.10.1.custom.min.js'); ?>"></script>
        <script type="text/javascript"  src="<?php echo $this->baseUrl('/js/jquery.ui.core.js'); ?>"></script>
        <script type="text/javascript"  src="<?php echo $this->baseUrl('/js/jquery.ui.widget.js'); ?>"></script>
        <script type="text/javascript"  src="<?php echo $this->baseUrl('/js/jquery.ui.button.js'); ?>"></script>
        
        <script type="text/javascript"  src="<?php echo $this->baseUrl('/js/jquery.form.js'); ?>"></script>
        <script type="text/javascript"  src="<?php echo $this->baseUrl('/js/jquery.alphanumeric.js'); ?>"></script>

        <script type="text/javascript"  src="<?php echo $this->baseUrl('/js/jquery.maskMoney.js'); ?>"></script>
        
        <script type="text/javascript"  src="<?php echo $this->baseUrl('/js/jquery.mask.js'); ?>"></script>
        <script type="text/javascript"  src="<?php echo $this->baseUrl('/js/jquery.validate.js'); ?>"></script>
        <script type="text/javascript"  src="<?php echo $this->baseUrl('/js/additional-methods.js'); ?>"></script>
        
        
        <script type="text/javascript"  src="<?php echo $this->baseUrl('/js/jquery.populate.js'); ?>"></script>
        <script type="text/javascript"  src="<?php echo $this->baseUrl('/js/messages_ptbr.js'); ?>"></script>
        
        <script type="text/javascript"  src="<?php echo $this->baseUrl('/js/jquery.numeric.pack.js'); ?>"></script>
        <script type="text/javascript"  src="<?php echo $this->baseUrl('/js/jquery.blockui.js'); ?>"></script>        
        
        <script type="text/javascript"  src="<?php echo $this->baseUrl('/js/global.js'); ?>"></script>
        
        
    </head>
    <body>
        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                            <li>
                                <a href="/clientes/index" onclick="">Clientes</a>
                            </li>
                            <li>
                                <a href="" onclick="">Cursos</a>
                            </li>
                            <li>
                                <a href="<?php echo $this->baseUrl('admin/usuario'); ?>" onclick="">Usuários</a>
                            </li>
                            <li>
                                <a href="/turmas/index" onclick="">Turmas</a>
                            </li>
                            <li>
                                <a href="" onclick="">Certificados</a>
                            </li>
                        </ul>
                        <ul class="nav pull-right">
                            <li>
                                <?php
                                $auth = Zend_Auth::getInstance();
                                if ($auth->hasIdentity()):
                                    ?>


                                    <a>Logado como: 
                                        <?php
                                        $usuario = Zend_Auth::getInstance()->getIdentity();
                                        echo $usuario->tx_nome;
                                        ?>
                                    </a>
                                <li>
                                    <a id="botao_sair" href="/index/sair">Sair</a>
                                </li>
                            <?php endif; ?>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div id="content">

            <!-- menu  -->

            <span style="color: red" id="divMsg">
                <?php if ($this->msg): ?>
                    <?php if (is_array($this->msg)): ?>

                        <?php echo implode("; ", $this->msg); ?>
                    <?php else: ?>
                        <?php echo $this->msg ?>
                    <?php endif; ?>
                <?php endif; ?>
            </span>
            <h1><?php echo $this->titlePage ?></h1>
            <?php echo $this->layout()->content; ?>
        </div>
    </body>
</html>
<script>
    //$(document).ready(function() {
    //Melhora aparência dos botões
    //$("#botao_sair").button(); 
    //});
</script>

