<div class="container" style="margin-top: 50px">
    <form id="form_aluno" class="form-horizontal well" action="<?php echo $this->baseUrl('/aluno/aluno/salvar'); ?>" method="post">
        <fieldset>
            <legend><?php echo $this->titulo; ?></legend>
            <input type="hidden" name="aluno[id_aluno]" id="aluno-id_aluno"/>
            <input type="hidden" class="required" name="aluno[id_cliente]" id="aluno-id_cliente"/>

            <fieldset style="margin-top: -40px">
                <h5 style="margin-top: 40px">Dados do Cliente</h5>
                <hr style="margin-top: -10px">
                

                <div  class="control-group">
                    <label class="control-label" for="">Nome/Razão Social</label>
                    <div class="controls">
                        <span class="help-block label" id="dados-cliente_tx_nome_razao_social"></span>
                    </div>
                </div>

                <div class="control-group">
                    <label class="control-label" for="">CPF/CNPJ</label>
                    <div class="controls">
                        <span class="help-block label" id="dados-cliente_tx_cpf_cnpj"></span>
                    </div>
                </div>

                <div class="control-group">
                    <label class="control-label" for="">Tipo</label>
                    <div class="controls">
                        <span class="help-block label" id="dados-cliente_tx_tipo"></span>
                    </div>
                </div>
            </fieldset>                                                   

            <fieldset style="margin-top: -40px">
                <h5 style="margin-top: 40px">Dados do Aluno</h5>
                <hr style="margin-top: -10px">         
                <div style="margin-left: 100px; margin-bottom: 20px">
                    <label style="display: inline-block; margin-right: 10px" for="aluno-tx_nome_aluno">Nome*</label>
                    <input class="input-prepend input-large required" style="margin-right: 30px" type="text" name="aluno[tx_nome_aluno]" id="aluno-tx_nome_aluno" maxlength="45"/>
                    <label style="display: inline-block; margin-right: 10px" for="aluno-tx_cargo">Profissão</label>
                    <input class="input-prepend input-medium" style="margin-right: 25px" type="text" name="aluno[tx_cargo]" id="aluno-tx_cargo" maxlength="45"/>
                </div>
                
                <div style="margin-left: 118px">
                    <label style="display: inline-block; margin-right: 10px" for="aluno-tx_rg">RG*</label>
                    <input class="input-prepend input-medium required" style="margin-right: 117px" type="text" name="aluno[tx_rg]" id="aluno-tx_rg" maxlength="9"/>
                    <label style="display: inline-block; margin-right: 10px" for="aluno-tx_cpf">CPF*</label>
                    <input readonly="readonly" class="input-prepend input-medium required cpf validarCPF" style="margin-right: 25px" type="text" name="aluno[tx_cpf]" id="aluno-tx_cpf" maxlength="14"/>
                </div>

            </fieldset>  
            
            <fieldset style="margin-top: -40px">
                <h5 style="margin-top: 40px">Dados de Login</h5>
                <hr style="margin-top: -10px">  
                <div style="margin-left: 100px; margin-bottom: 20px">
                    <input type="hidden" name="usuario[id_usuario]" id="usuario-id_usuario">
                    <label style="display: inline-block; margin-right: 10px" for="usuario-tx_nome">Nome*</label>
                    <input class="input-prepend input-large required" style="margin-right: 30px" type="text" name="usuario[tx_nome]" id="usuario-tx_nome" maxlength="45"/>                     
                </div>
                
                <div style="margin-left: 100px; margin-bottom: 20px">                    
                    <label style="display: inline-block; margin-right: 10px" for="usuario-tx_login">Login*</label>
                    <input class="input-prepend input-large required" style="margin-right: 30px" type="text" name="usuario[tx_login]" id="usuario-tx_login" maxlength="45"/> 
                    <label style="display: inline-block; margin-right: 10px" for="usuario-tx_email">Email</label>
                    <input class="input-prepend input-large email" style="margin-right: 30px" type="text" name="usuario[tx_email]" id="usuario-tx_email" maxlength="45"/>                    
                </div>
                               
                <div style="margin-left: 100px; margin-bottom: 20px">
                    <label style="display: inline-block; margin-right: 10px" for="usuario-tx_senha">Senha*</label>
                    <input class="input-prepend input-large required" style="margin-right: 30px" type="password" name="usuario[tx_senha]" id="usuario-tx_senha" maxlength="45"/>
                    <label style="display: inline-block; margin-right: 10px" for="repetir_senha">Repetir Senha*</label>
                    <input class="input-prepend input-large required" equalTo="#usuario-tx_senha" style="margin-right: 30px" type="password" name="repetir_senha" id="repetir_senha" maxlength="45"/>                                                            
                </div>                
            </fieldset>

            <div class="form-actions">
                <input class="btn btn-primary" id="btEnviar" type="submit" value="Salvar"/>
                <input class="btn" id="btVoltar" onclick="window.back()" type="button" value="Cancelar"/>
            </div>
        </fieldset>
    </form>
</div>

<div id="mensagemAluno">    
</div>

<script>    
    var dataForm = <?php echo Zend_Json::encode(array('aluno' => $this->aluno, 'usuario' => $this->usuario)); ?>;      
    
    function callBackPesquisarCliente(dataCliente) {        
        $('#aluno-id_cliente').val(dataCliente.id_cliente);
        if(dataCliente.tx_tipo_cliente == 'F') {
            $('#dados-cliente_tx_tipo').html('Pessoa Física');
            $('#dados-cliente_tx_nome_razao_social').html(dataCliente.tx_nome);
            $('#dados-cliente_tx_cpf_cnpj').html(dataCliente.tx_cpf);            
        } else {
            $('#dados-cliente_tx_tipo').html('Pessoa Jurídica');
            $('#dados-cliente_tx_nome_razao_social').html(dataCliente.tx_razao_social);
            $('#dados-cliente_tx_cpf_cnpj').html(dataCliente.tx_cnpj);
        }
    }
    
    $(function(){   
        $('#form_aluno').populate(dataForm);
                
        $('#btLimparCliente').click(function() {
            $('.help-block').html('');
        });
        
    <?php if (!empty($this->usuario['tx_senha'])) { ?>
        $('#repetir_senha').val('<?=$this->usuario['tx_senha']?>');
    <?php } ?>
        
    <?php if (!empty($this->cliente)) { ?>
        callBackPesquisarCliente(<?php echo Zend_Json::encode($this->cliente) ?>);
    <?php } ?>
           
        //Código responsável por nao permitir que espaços sejam inseridos no login
        $("#usuario-tx_login").on({
            keydown: function(e) {
              if (e.which === 32)
                return false;
            },
            change: function() {
              this.value = this.value.replace(/\s/g, "");
            }
        });   
           
           
        $('#form_aluno').validate({
            submitHandler: function(form) {
                if($('#aluno-id_cliente').val() == '') {
                    $('#mensagemAluno').html("Selecione o Cliente responsável por esse Aluno");                            
                    $("#mensagemAluno").dialog({
                        modal: true,
                        buttons: {
                            Ok: function() {
                                $(this).dialog("close");                                        
                            }
                        }
                    });
                    $('#mensagemAluno').dialog("open");
                } else {
                    if($('#usuario-tx_senha').val() != $('#repetir_senha').val()) {
                        $('#mensagemAluno').html("A senha deve ser a mesma nos dois campos, verifique");
                        $("#mensagemAluno").dialog({
                            modal: true,
                            buttons: {
                                Ok: function() {
                                    $(this).dialog("close");                                            
                                }
                            }
                        });
                    } else {
                        jQuery(form).ajaxSubmit({
                            dataType:  'json', 
                            success: function(r){
                                if(r.tipo == 'sucesso'){
                                    $('#mensagemAluno').html(r.msg);
                                    $("#mensagemAluno").dialog({
                                        modal: true,
                                        buttons: {
                                            Ok: function() {
                                                $(this).dialog("close");
                                                window.location = r.url;
                                            }
                                        }
                                    });

                                } else {
                                    $('#mensagemAluno').html(r.msg);                            
                                    $("#mensagemAluno").dialog({
                                        modal: true,
                                        buttons: {
                                            Ok: function() {
                                                $(this).dialog("close");                                        
                                            }
                                        }
                                    });
                                    $('#mensagemAluno').dialog("open");                            
                                }
                            } 
                        });
                    }
                }
            } 
        });
    });
        
</script>