<div class="container" style="margin-top: 50px">
    <div id="div_mensagem"><?php echo ($this->msg != null) ? $this->msg[0] : "" ?></div>
    <form class="form-horizontal well" action="#" method="post">        
        <fieldset>
            <legend><?php echo $this->titulo; ?></legend>                        
            
            <!-- INICIO dos campos de busca -->
            <div class="form-actions" style="padding-left: 20px!important">
                <div class="control-group">
                    <label class="control-label" for="tx_nome_treinamento">Nome do Treinamento</label>
                    <div class="controls">
                        <input class="input-xlarge" type="text" name="tx_nome_treinamento" id="tx_nome_treinamento" maxlength="18"/>
                    </div>
                </div>
                <div style="margin-left: 72px">
                    <label style="display: inline-block; margin-right: 16px" for="data_inicial">Data/Período</label>
                    <input class="input-prepend input-medium" style="margin-right: 20px" type="text" name="data_inicial" id="data_inicial" value=""/>
                    a
                    <label style="display: inline-block; margin-right: 16px" for="data_final"></label>
                    <input class="input-prepend input-medium" style="margin-right: 25px; margin-left: 15px" type="text"  name="data_final" id="data_final" value=""/>
                </div>
                <div style="margin-bottom: -20px; margin-top: -0px" class="form-actions">
                    <input class="btn btn-primary" id="btGerarRelatorioTreinamentos" type="button" value="Gerar Relatório"/>
                </div>
            </div>
            <!-- FIM dos campos de busca -->            
        </fieldset>                
    </form>
</div>

<script>
    $(function(){                                                     
        $('#data_inicial').mask("99/99/9999");
        $('#data_final').mask("99/99/9999");
        
        $('#btGerarRelatorioTreinamentos').click(function(){            
            tx_nome_treinamento = urlencodeGet($('#tx_nome_treinamento').val());
            data_inicial = urlencodeGet($('#data_inicial').val());
            data_final = urlencodeGet($('#data_final').val());
            
            window.open('<?php echo $this->baseUrl('admin/relatorio/relatorio-treinamentos/nome_treinamento/'); ?>' + tx_nome_treinamento + '/data_inicial/' + data_inicial + '/data_final/' + data_final);
        });                
    });     
</script>