<div class="container" style="margin-top: 50px">
    <div id="div_mensagem"><?php echo ($this->msg != null) ? $this->msg[0] : "" ?></div>
    <form class="form-horizontal well" action="#" method="post">        
        <fieldset>
            <legend><?php echo $this->titulo; ?>
                <button id="novo_cliente" style="float: right; margin-top: 2px" class="btn btn-primary" type="button">Novo Cliente</button>
            </legend>
            <!--            <div style="clear: both;"></div>-->

            <!-- INICIO dos campos de busca -->
            <div class="form-actions" style="padding-left: 20px!important; margin-top: 0px">
                <div class="control-group">
                    <label class="control-label" for="tx_tipo_cliente">Tipo </label>
                    <div class="controls">
                        <select id="cliente-tx_tipo_cliente" name="cliente[tx_tipo_cliente]">                            
                            <option selected value="F">Pessoa Física</option>
                            <option value="J">Pessoa Jurídica</option>            
                        </select>
                    </div>
                </div>
                
                <div class="dados_pessoa_juridica" style="margin-left: 72px; margin-bottom: 30px">
                    <label style="display: inline-block; margin-right: 14px" for="cliente-tx_razao_social">Razão Social</label>
                    <input class="input-prepend" style="margin-right: 25px" type="text" name="cliente[tx_razao_social]" maxlength="60" id="cliente-tx_razao_social"/>
                    <label style="display: inline-block; margin-right: 10px" for="cliente-tx_cnpj">CNPJ</label>
                    <input class="input-prepend cnpj validarCNPJ" style="margin-right: 25px" type="text" name="cliente[tx_cnpj]" id="cliente-tx_cnpj" maxlength="18"/>
                </div>

                <div class="dados_pessoa_fisica" style="margin-left: 121px; margin-bottom: 30px">
                    <label style="display: inline-block; margin-right: 14px" for="cliente-tx_nome">Nome</label>
                    <input class="input-prepend required" style="margin-right: 25px" type="text" name="cliente[tx_nome]" id="cliente-tx_nome" maxlength="45"/>
                    <label style="display: inline-block; margin-right: 10px" for="cliente-tx_cpf">CPF</label>
                    <input class="input-prepend cpf validarCPF" style="margin-right: 25px" type="text" name="cliente[tx_cpf]" id="cliente-tx_cpf" maxlength="14"/>
                </div>
                
                <div style="margin-bottom: -20px; margin-top: -20px" class="form-actions">
                    <input class="btn btn-primary" id="btBuscarCliente" type="button" value="Buscar"/>
                </div>

            </div>
            <!-- FIM dos campos de busca -->            
        </fieldset>

        <div id="divResCliente"></div>
    </form>


</div>

<script>
    $(function(){             
        //$('#div_usuario').load('/usuario/grid/'); 
        
        $('.dados_pessoa_juridica').hide();
        //Altera a exibição dos campos no formulario conforme o tipo de cliente
        $('#cliente-tx_tipo_cliente').change(function(){
            if($('#cliente-tx_tipo_cliente').val() == 'F') {
                $('.dados_pessoa_fisica').show();
                $('.dados_pessoa_juridica').hide();
            }
            
            if($('#cliente-tx_tipo_cliente').val() == 'J') {
                $('.dados_pessoa_fisica').hide();
                $('.dados_pessoa_juridica').show();
            }                       
        });
        
        $('#divResCliente').load('<?php echo $this->baseUrl('admin/cliente/grid'); ?>');
        $('#btBuscarCliente').click(function(){            
            tx_razao_social = urlencodeGet($('#cliente-tx_razao_social').val());
            tx_cnpj = urlencodeGet($('#cliente-tx_cnpj').val());
            tx_nome = urlencodeGet($('#cliente-tx_nome').val());
            tx_cpf = urlencodeGet($('#cliente-tx_cpf').val());
            tx_tipo_cliente = $('#cliente-tx_tipo_cliente').val();
            
            
            $('#divResCliente').load('<?php echo $this->baseUrl('admin/cliente/grid'); ?>'+'/tx_razao_social/' + tx_razao_social + '/tx_cnpj/' + tx_cnpj + '/tx_nome/' + tx_nome + '/tx_cpf/' + tx_cpf + '/tx_tipo_cliente/' + tx_tipo_cliente);
        });
        
        //Carrega formulario de novo cliente com jquery
        $('#novo_cliente').click(function(){
            window.location = '<?php echo $this->baseUrl('admin/cliente/form'); ?>';
        });
    }); 
    
</script>