<table class="table table-bordered table-striped table-hover">
    <tr>
        <th>Aluno</th>
        <th>CPF</th>
        <th>Treinamento</th>        
        <th>Data Início</th>
        <th>Data Fim</th>
        <th>Ações</th>
    </tr>

    <tr class="alt" >
        <?php foreach ($this->paginator as $k => $matricula): ?>
        <tr class="<?php echo ($k % 2 == 0) ? 'alt' : '' ?>">
            <td>
                <?php
                echo $matricula['tx_nome_aluno'];
                ?>
            </td>
            <td>
                <?php
                echo $matricula['tx_cpf'];
                ?>
            </td>
            <td>
                <?php
                echo $matricula['tx_nome_treinamento'];
                ?>
            </td>            
            <td>
                <?php echo $this->String($matricula['dt_inicio_treinamento'])->reverseDate(); ?>
            </td>            
            <td>
                <?php echo $this->String($matricula['dt_termino_treinamento'])->reverseDate(); ?>
            </td>
            <td>                
                <a class="btExcluir" href="<?php echo $this->baseUrl('/admin/matricula/excluir') ?>/id/<?php echo $matricula['id_matricula'] ?>">
                    <img src="/img/delete-icon.gif" title="Excluir Registro" />
                </a>
            </td>
        </tr>    
    <?php endforeach; ?>

</table>

<?php echo $this->paginationControl($this->paginator, 'Sliding', 'my_pagination_control.phtml'); ?>

<div id="confirmacao">
    <span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>Deseja realmente excluir esse Matricula?
</div>

<div id="erroMat">
    Erro    
</div>

<div id="sucessoMat">
    Sucesso    
</div>

<script>        
    $(function(){       
                
        $( "#sucessoMat" ).dialog({
            modal: true,
            autoOpen: false
        });
        
        $( "#erroMat" ).dialog({
            modal: true,
            autoOpen: false
        });
                
        $('.btExcluir').click(function(){
            
            url = $(this).attr('href');
            $("#confirmacao").dialog("open");
            
            return false;
        });
                
        $("#confirmacao").dialog({
            resizable: false,
            height:250,
            width:500,
            modal: true,
            autoOpen: false,
                
            buttons: {
                "Ok": function() {
                    $.get(url, null, function(retorno){
                        if(retorno.tipo == 'sucesso'){
                            $('#sucessoMat').html(retorno.msg);
                            
                            $('#sucessoMat').dialog({
                                buttons: {
                                    Ok: function() {
                                        $( this ).dialog( "close" );
                                    }
                                }
                            });
                            $('#sucessoMat').dialog("open");    
                            $('#div_matricula').load('<?php echo $this->baseUrl('admin/matricula/grid'); ?>');                                
                        } else {
                            $('#sucessoMat').html(retorno.msg);                            
                            $('#sucessoMat').dialog({
                                buttons: {
                                    Ok: function() {
                                        $( this ).dialog( "close" );
                                    }
                                }
                            });
                            $('#sucessoMat').dialog("open");
                            $('#div_matricula').load('<?php echo $this->baseUrl('admin/matricula/grid'); ?>');
                        }                    
                    }, 'json');
                    $( this ).dialog("close");
                    
                },
                "Cancel": function() {
                    $('#div_matricula').load('<?php echo $this->baseUrl('admin/matricula/grid'); ?>');
                    $( this ).dialog( "close" );
                        
                }
                    
            }
                
        });
        
    })
    
</script>