<div class="container" style="margin-top: 50px">
    <div id="div_mensagem"><?php echo ($this->msg != null) ? $this->msg[0] : "" ?></div>
    <form id="form_matricula_alunos" class="form-horizontal well" action="<?php echo $this->baseUrl('/admin/matricula/salvar-alunos-cliente'); ?>" method="post">
        <fieldset>
            <legend><?php echo $this->titulo; ?></legend>
            <input type="hidden" name="matricula[id_turma]" id="matricula-id_turma"/>
            <input type="hidden" name="matricula[id_cliente]" id="matricula-id_cliente"/>
            
            <fieldset style="margin-top: -40px">
                <h5 style="margin-top: 40px">Dados da Turma</h5>
                <hr style="margin-top: -10px">
                <div align="right" class="control-group">
                    <input class="btn btn-primary" id="btModalTurma" type="button" value="Buscar Turma"/>
                    <input class="btn" id="btLimparTurma" type="button" value="Limpar"/>
                </div>
                
                <div style="margin-top: -50px" class="control-group">
                    <label class="control-label" for="">Treinamento</label>
                    <div class="controls">
                        <span class="help-block label dados_turma" id="dados-tx_nome_treinamento"></span>
                    </div>
                </div>

                <div class="control-group">
                    <label class="control-label" for="">Período</label>
                    <div class="controls">
                        <span class="help-block label dados_turma" id="dados-data_turma"></span>
                    </div>
                </div>              
            </fieldset>
            
            <fieldset style="margin-top: -40px">
                <h5 style="margin-top: 40px">Dados do Cliente</h5>
                <hr style="margin-top: -10px">
                <div align="right" class="control-group">
                    <input class="btn btn-primary" id="btModalCliente" type="button" value="Buscar Cliente"/>
                    <input class="btn" id="btLimparCliente" type="button" value="Limpar"/>
                </div>

                <div style="margin-top: -50px" class="control-group">
                    <label class="control-label" for="">Nome/Razão Social</label>
                    <div class="controls">
                        <span class="help-block label dados_cliente" id="dados-cliente_tx_nome_razao_social"></span>
                    </div>
                </div>

                <div class="control-group">
                    <label class="control-label" for="">CPF/CNPJ</label>
                    <div class="controls">
                        <span class="help-block label dados_cliente" id="dados-cliente_tx_cpf_cnpj"></span>
                    </div>
                </div>

                <div class="control-group">
                    <label class="control-label" for="">Tipo</label>
                    <div class="controls">
                        <span class="help-block label dados_cliente" id="dados-cliente_tx_tipo"></span>
                    </div>
                </div>
            </fieldset>
            
            <div id="divResAlunosMatriculados"></div>
            
            <div class="form-actions" style="display: none" id="botaoSubmit">
                <input class="btn btn-primary" id="btEnviar" type="submit" value="Salvar Matrículas"/>                                
            </div>
        </fieldset>
    </form>    
</div>

<?php    
    echo $this->render('partials/modal-pesquisa-turma.phtml');
?>

<?php
    echo $this->render('partials/modal-pesquisa-cliente.phtml');
?>

<div id="mensagemMatricula">    
</div>

<script>            
    function callBackPesquisarTurma(dataTurma) {                
        ShowMsgAguarde();
        $('#matricula-id_turma').val(dataTurma.id_turma);
        $('#dados-tx_nome_treinamento').html(dataTurma.tx_nome_treinamento);
        dataInicio = reverseDate(dataTurma.dt_inicio_treinamento);
        dataFim = reverseDate(dataTurma.dt_termino_treinamento);
        $('#dados-data_turma').html(dataInicio + " à " + dataFim);	                
        CloseMsgAguarde();
    }
    
    function callBackPesquisarCliente(dataCliente) {  
        ShowMsgAguarde();
        $('#matricula-id_cliente').val(dataCliente.id_cliente);
        if(dataCliente.tx_tipo_cliente == 'F') {
            $('#dados-cliente_tx_tipo').html('Pessoa Física');
            $('#dados-cliente_tx_nome_razao_social').html(dataCliente.tx_nome);
            $('#dados-cliente_tx_cpf_cnpj').html(dataCliente.tx_cpf);            
        } else {
            $('#dados-cliente_tx_tipo').html('Pessoa Jurídica');
            $('#dados-cliente_tx_nome_razao_social').html(dataCliente.tx_razao_social);
            $('#dados-cliente_tx_cpf_cnpj').html(dataCliente.tx_cnpj);
        }
        
        if(dataCliente.id_cliente == '') {
            CloseMsgAguarde();
             $('#mensagemCliente p').html("Um erro ocorreu, por favor, busque novamente o Cliente e clique em Selecionar");                
             $('#mensagemCliente').dialog({
                 buttons: {
                     "Ok": function() {
                         $(this).dialog("close");                            
                     }
                 }
             });
             $('#mensagemCliente').dialog("open"); 
        } else {
             $('#divResAlunosMatriculados').load('<?php echo $this->baseUrl('admin/matricula/grid-matricula-grupo-cliente'); ?>'+'/id_cliente/' + dataCliente.id_cliente);
        }
        CloseMsgAguarde();
    }
    
    $(function(){                           
        $('#btLimparTurma').click(function() {
            $('.dados_turma').html('');
            $('#matricula-id_turma').val('');
        });
        
        $('#btModalTurma').click(function() {
            openModalPesquisaTurma();
        });
        
        $('#mensagemMatricula').dialog({
            autoOpen: false
        });
        
        $('#btLimparCliente').click(function() {
            $('.dados_cliente').html('');
            $('#matricula-id_cliente').val('');
        });
        
        $('#btModalCliente').click(function() {
            openModalPesquisaCliente();
        });
        
        $('#mensagemCliente').dialog({
            autoOpen: false
        });
            
        $('#form_matricula_alunos').validate({
            submitHandler: function(form) {                
                salva = true;
                if($('#matricula-id_turma').val() == '') {
                    salva = false;
                    $('#mensagemMatricula').html("Selecione a Turma que os Alunos serãos matriculados");                            
                    $("#mensagemMatricula").dialog({
                        modal: true,
                        buttons: {
                            Ok: function() {
                                $(this).dialog("close");                                        
                            }
                        }
                    });
                    $('#mensagemMatricula').dialog("open");
                } else { 
                    if($('#matricula-id_cliente').val() == '') {
                        salva = false;
                        $('#mensagemMatricula').html("Selecione o Cliente responsável pelos Alunos");
                        $("#mensagemMatricula").dialog({
                            modal: true,
                            buttons: {
                                Ok: function() {
                                    $(this).dialog("close");                                        
                                }
                            }
                        });
                        $('#mensagemMatricula').dialog("open");
                        return;
                    }
                    encontrou = false;
                    $('.alunoCliente').each(function () {
                        if($(this).is(':checked')) {
                           encontrou = true; 
                        }
                    });
                    if(encontrou == false) {
                        salva = false;
                        $('#mensagemMatricula').html("Deve existir pelo menos um Aluno para realizar a matrícula!");
                        $("#mensagemMatricula").dialog({
                            modal: true,
                            buttons: {
                                Ok: function() {
                                    $(this).dialog("close");                                        
                                }
                            }
                        });
                        $('#mensagemMatricula').dialog("open");
                        return;
                    }
                    if(salva) {
                        jQuery(form).ajaxSubmit({
                            dataType:  'json', 
                            success: function(r){
                                if(r.tipo == 'sucesso'){
                                    $('#mensagemMatricula').html(r.msg);                            
                                    $("#mensagemMatricula").dialog({
                                        modal: true,
                                        buttons: {
                                            Ok: function() {
                                                $(this).dialog("close");
                                                window.location = r.url;
                                            }
                                        }
                                    });
                                    $('#mensagemMatricula').dialog("open");                                    
                                } else {
                                    $('#mensagemMatricula').html(r.msg);                            
                                    $("#mensagemMatricula").dialog({
                                        modal: true,
                                        buttons: {
                                            Ok: function() {
                                                $(this).dialog("close");                                        
                                            }
                                        }
                                    });
                                    $('#mensagemMatricula').dialog("open");                            
                                }
                            } 
                        });
                    }
                }
            } 
        });
    });
        
</script>
