<div class="container" style="margin-top: 50px">
    <div id="div_mensagem"><?php echo ($this->msg != null) ? $this->msg[0] : "" ?></div>
    <form id="form_importar_alunos" enctype="multipart/form-data" class="form-horizontal well" action="<?php echo $this->baseUrl('/admin/aluno/salvar-importacao'); ?>" method="post">
        <fieldset>
            <legend><?php echo $this->titulo; ?></legend>            
            <input type="hidden" class="required" name="aluno[id_cliente]" id="aluno-id_cliente"/>
            <input type="hidden" class="required" name="aluno[url_planilha]" id="aluno-url_planilha"/>
            
            <fieldset>
                <legend>Dados do Cliente</legend>
                
                <div class="control-group">
                    <input class="btn" id="btModalCliente" type="button" value="Buscar"/>
                    <input class="btn" id="btLimparCliente" type="button" value="Limpar"/>
                </div>
                
                <div class="control-group">
                    <label class="control-label" for="">Nome/Razão Social</label>
                    <div class="controls">
                        <span class="help-block label" id="dados-cliente_tx_nome_razao_social"></span>
                    </div>
                </div>
                
                <div class="control-group">
                    <label class="control-label" for="">CPF/CNPJ</label>
                    <div class="controls">
                        <span class="help-block label" id="dados-cliente_tx_cpf_cnpj"></span>
                    </div>
                </div>
                
                <div class="control-group">
                    <label class="control-label" for="">Tipo</label>
                    <div class="controls">
                        <span class="help-block label" id="dados-cliente_tx_tipo"></span>
                    </div>
                </div>
            </fieldset>                                                   
            
            <fieldset>
                <legend>Dados do Alunos</legend>                
                <div class="control-group">
                    <label class="control-label" for="aluno-tx_nome_aluno">Planilha</label>
                    <div class="controls">                        
                        <input class="input-xlarge required" type="file" name="fileUploadAlunos" id="fileUploadAlunos"/>
                    </div>
                </div> 
                                                                               
            </fieldset>             
                                                    
            <div class="form-actions">
                <input class="btn" id="btLerPLanilha" type="button" value="Ler Planilha"/>                                
            </div>
            
            <div id="divResAlunosImportados"></div>
            
            <div class="form-actions" style="display: none" id="botaoSubmit">
                <input class="btn btn-primary" id="btEnviar" type="submit" value="Salvar Alunos"/>                                
            </div>
        </fieldset>
    </form>
</div>

<?php    
    echo $this->render('partials/modal-pesquisa-cliente.phtml');
?>

<div id="mensagemAluno">    
</div>

<script>            
    function callBackPesquisarCliente(dataCliente) {        
        $('#aluno-id_cliente').val(dataCliente.id_cliente);
        if(dataCliente.tx_tipo_cliente == 'F') {
            $('#dados-cliente_tx_tipo').html('Pessoa Física');
            $('#dados-cliente_tx_nome_razao_social').html(dataCliente.tx_nome);
            $('#dados-cliente_tx_cpf_cnpj').html(dataCliente.tx_cpf);            
        } else {
            $('#dados-cliente_tx_tipo').html('Pessoa Jurídica');
            $('#dados-cliente_tx_nome_razao_social').html(dataCliente.tx_razao_social);
            $('#dados-cliente_tx_cpf_cnpj').html(dataCliente.tx_cnpj);
        }
    }
    
    $(function(){                           
        $('#btLimparCliente').click(function() {
            $('.help-block').html('');
        });
        
        $('#btModalCliente').click(function() {
            openModalPesquisaCliente();
        });
        
        $('#mensagemCliente').dialog({
            autoOpen: false
        });                  
        
        $('#btLerPLanilha').click(function() {
            url_planilha = urlencodeGet($('#aluno-url_planilha').val());
            if(url_planilha == '') {
                $('#mensagemAluno').html('Selecione a planilha antes de realizar a leitura dos Alunos');
                $('#mensagemAluno').dialog({
                    modal: true,
                    title: "ATENÇÃO",
                    buttons: {
                        "Ok": function() {
                            $( this ).dialog( "close" );
                        }
                    }
                });
                $('#mensagemAluno').dialog("open");
            } else {
                ShowMsgAguarde();
                $('#divResAlunosImportados').load('<?php echo $this->baseUrl('admin/aluno/ler-planilha'); ?>'+'/url_planilha/' + url_planilha, function() {
                    CloseMsgAguarde();
                });
            }
        });
        
        $('#fileUploadAlunos').change(function(){
            url_original = $('#form_importar_alunos').attr('action');
            ShowMsgAguarde();
            $('#form_importar_alunos').ajaxSubmit({
                url: '<?php echo $this->baseUrl('/admin/aluno/upload-aluno'); ?>',
                success: function(data){                
                    $('#form_importar_alunos').attr('action', url_original);
                    $('#form_importar_alunos').removeAttr('target');                    
                    $('#mensagemAluno').html(data.msg);                            
                    $('#mensagemAluno').dialog({
                        modal: true,
                        title: "ATENÇÃO",
                        buttons: {
                            "Ok": function() {
                                $( this ).dialog( "close" );
                            }
                        }
                    });
                    $('#mensagemAluno').dialog("open");
                    
                    if(data.tipo == 'sucesso') {
                        $('#aluno-url_planilha').val(data.urlArquivo);
                        $('#divResAlunosImportados').html('');
                        $('#botaoSubmit').hide();
                    } else {
                        $('#fileUploadAlunos').val('');
                    }
                }
            });
            CloseMsgAguarde();
        });
            
        $('#form_importar_alunos').validate({
            submitHandler: function(form) {
                $('.danger').removeClass('warning');
                salva = true;
                if($('#aluno-id_cliente').val() == '') {
                    $('#mensagemAluno').html("Selecione o Cliente responsável por esses Alunos");                            
                    $("#mensagemAluno").dialog({
                        modal: true,
                        buttons: {
                            Ok: function() {
                                $(this).dialog("close");                                        
                            }
                        }
                    });
                    $('#mensagemAluno').dialog("open");
                } else {
                    salva = true;
                    encontrou = false;
                    $('.tx_salva-required').each(function () {
                        id_linha = $(this).attr('id_linha');                        
                        if($(this).is(':checked')) { 
                            encontrou = true;
                            if(($('#nome-required'+id_linha).val() == '') || ($('#cpf-required'+id_linha).val() == '')) {                            
                                salva = false;
                                $(this).parent().parent().addClass('warning');
                                $('#mensagemAluno').html("Um aluno não pode ser salvo sem Nome ou CPF, verifique!");
                                $("#mensagemAluno").dialog({
                                    modal: true,
                                    buttons: {
                                        Ok: function() {
                                            $(this).dialog("close");                                        
                                        }
                                    }
                                });
                                $('#mensagemAluno').dialog("open");
                                return;
                            } 
                            if(!validarCPF($('#cpf-required'+id_linha).val())) {
                                salva = false;
                                $(this).parent().parent().addClass('warning');
                                $('#mensagemAluno').html("Um aluno não pode ser salvo com CPF inválido, verifique!");
                                $("#mensagemAluno").dialog({
                                    modal: true,
                                    buttons: {
                                        Ok: function() {
                                            $(this).dialog("close");                                        
                                        }
                                    }
                                });
                                $('#mensagemAluno').dialog("open");
                                return;
                            }
                        }
                    });
                    if(encontrou == false) {
                        $('#mensagemAluno').html("Selecione pelo menos UM aluno para realizar a importação!");
                        $("#mensagemAluno").dialog({
                            modal: true,
                            buttons: {
                                Ok: function() {
                                    $(this).dialog("close");                                        
                                }
                            }
                        });
                        $('#mensagemAluno').dialog("open");
                        return;
                    }
                    if(salva) {
                        jQuery(form).ajaxSubmit({
                            dataType:  'json', 
                            success: function(r){
                                if(r.tipo == 'sucesso'){
                                    $('#mensagemAluno').html(r.msg);                            
                                    $("#mensagemAluno").dialog({
                                        modal: true,
                                        buttons: {
                                            Ok: function() {
                                                $(this).dialog("close");
                                                window.location = r.url;
                                            }
                                        }
                                    });
                                    $('#mensagemAluno').dialog("open");
                                    //$('#div_mensagem').html(r.msg);                                    
                                } else {
                                    $('#mensagemAluno').html(r.msg);                            
                                    $("#mensagemAluno").dialog({
                                        modal: true,
                                        buttons: {
                                            Ok: function() {
                                                $(this).dialog("close");                                        
                                            }
                                        }
                                    });
                                    $('#mensagemAluno').dialog("open");                            
                                }
                            } 
                        });
                    }
                }
            } 
        });
    });
        
</script>