<div class="container" style="margin-top: 50px">
    <div id="div_mensagem"><?php echo ($this->msg != null) ? $this->msg[0] : "" ?></div>
    <form class="form-horizontal well" action="#" method="post">        
        <fieldset>
            <legend><?php echo $this->titulo; ?></legend>
            
            <!-- Botão novo alinhado a direita -->
            <input class="btn btn-primary" id="novo_aluno" type="button" value="Novo Aluno" style="float: right"/>
            <div style="clear: both;"></div>
            
            <!-- INICIO dos campos de busca -->
            <div class="form-actions" style="padding-left: 20px!important">
                
                                
                <input class="btn btn-primary" id="btBuscarAluno" type="button" value="Buscar"/>
            </div>
            <!-- FIM dos campos de busca -->            
        </fieldset>
        
        <div id="divResAluno"></div>
    </form>


</div>

<script>
    $(function(){                                             
        //$('#divResCliente').load('<?php echo $this->baseUrl('admin/cliente/grid'); ?>');
        $('#btBuscarAluno').click(function(){            
            tx_razao_social = urlencodeGet($('#cliente-tx_razao_social').val());
            tx_cnpj = urlencodeGet($('#cliente-tx_cnpj').val());
            tx_nome = urlencodeGet($('#cliente-tx_nome').val());
            tx_cpf = urlencodeGet($('#cliente-tx_cpf').val());
            tx_tipo_cliente = $('#cliente-tx_tipo_cliente').val();
            
            
            $('#divResAluno').load('<?php echo $this->baseUrl('admin/cliente/grid'); ?>'+'/tx_razao_social/' + tx_razao_social + '/tx_cnpj/' + tx_cnpj + '/tx_nome/' + tx_nome + '/tx_cpf/' + tx_cpf + '/tx_tipo_cliente/' + tx_tipo_cliente);
        });
        
        //Carrega formulario de novo aluno com jquery
        $('#novo_aluno').click(function(){
            window.location = '/admin/aluno/form';
        });
    }); 
    
</script>