<div class="container" style="margin-top: 50px">
    <form class="form-horizontal well" action="/admin/treinamento/form" method="post">
        <fieldset>
            <legend>
                <?php echo $this->titulo; ?>
                <button id="novo_treinamento" style="float: right; margin-top: 2px" class="btn btn-primary" type="button">Novo Treinamento</button>
            </legend>

            <div class="form-actions" style="padding-left: 20px!important; margin-top: 0px">
                <div class="control-group">
                    <label class="control-label" for="nome_treinamento">Nome do Treinamento</label>
                    <div class="controls">
                        <input class="input-xlarge" type="text" name="nome_treinamento" id="nome_treinamento" maxlength="18"/>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="nome_instrutor">Nome do Instrutor</label>
                    <div class="controls">
                        <input class="input-xlarge" type="text" name="nome_instrutor" id="nome_instrutor" maxlength="18"/>
                    </div>
                </div> 
                <div style="margin-bottom: -20px; margin-top: -20px" class="form-actions">
                    <input class="btn btn-primary" id="btBuscarTreinamento" type="button" value="Buscar"/>
                </div>
            </div>
        </fieldset>
        <div id="div_treinamento" >

        </div>
    </form>

</div>

<script>

    $(function(){

        $('#novo_treinamento').on("click", function(event){
            window.location = "/admin/treinamento/form";
        });
       
        $('#div_treinamento').load('<?php echo $this->baseUrl('admin/treinamento/grid'); ?>');
        $('#btBuscarTreinamento').click(function(){
            
            nome_treinamento = urlencodeGet($('#nome_treinamento').val());
            nome_instrutor = urlencodeGet($('#nome_instrutor').val());
            
            $('#div_treinamento').load('<?php echo $this->baseUrl('admin/treinamento/grid'); ?>'+'/nome_treinamento/' + nome_treinamento + '/nome_instrutor/' + nome_instrutor);
        });
        
    }); 
    
</script>