<div class="container" style="margin-top: 50px">
    <div id="div_mensagem"><?php echo ($this->msg != null) ? $this->msg[0] : "" ?></div>
    <form class="form-horizontal well" action="/admin/usuario/form" method="post">
        <legend><?php echo $this->titulo; ?></legend>
        <fieldset>
            <legend><?php $this->titulo; ?></legend>
            <div class="form-actions">
                <input class="btn btn-primary" id="novo_usuario" type="submit" value="Novo Usuário"/>
            </div>
        </fieldset>
    </form>

<div id="div_usuario">

</div>
</div>



<br />

<br />

<script>

    $(function(){
       //Melhora aparência dos botões
       //$( "input[type=submit], button" ).button();
       
     //$('#div_usuario').load('/usuario/grid/');
        
    }); 
    
</script>