<div class="container" style="margin-top: 50px">
    <form id="form_treinamento" class="form-horizontal well" action="<?php echo $this->baseUrl('/admin/treinamento/salvar') ?>/id/<?php echo $this->treinamento['id_treinamento'] ?>" method="post">

        <fieldset>
            <legend><?php echo $this->titulo; ?></legend>

            <div class="control-group">
                <label class="control-label" for="tx_nome_treinamento">Nome do treinamento</label>
                <div class="controls">
                    <input class="input-xlarge required" type="text" name="tx_nome_treinamento" id="tx_nome_treinamento" maxlength="45"/>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="tx_descricao">Descrição</label>
                <div class="controls">
                    <textarea class="descricao-treinamento" class="required" type="text" name="tx_descricao" id="tx_descricao"></textarea>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="tx_conteudo_programatico">Conteúdo Programático</label>
                <div class="controls">
                    <textarea class="conteudo-treinamento" class="required" type="text" name="tx_conteudo_programatico" id="tx_conteudo_programatico"></textarea>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="nr_carga_horaria">Carga Horária</label>
                <div class="controls">
                    <input class="input-medium numeric" type="text" name="nr_carga_horaria" id="nr_carga_horaria" value=""/>
                    <label style="display: inline-block; margin-right: 10px"><h6>Horas</h6></label>
                </div>
            </div>

            <h5>Instrutor</h5>
            <hr style="margin-top: -10px">
            <div style="margin-left: 60px">
                <label style="display: inline-block; margin-right: 10px" for="tx_nome_instrutor">Nome</label>
                <input class="input-prepend required" style="margin-right: 25px" type="text" name="tx_nome_instrutor" id="tx_nome_instrutor" value=""/>
                <label style="display: inline-block; margin-right: 10px" for="tx_funcao_instrutor">Função</label>
                <input class="input-prepend required" style="margin-right: 25px" type="text" name="tx_funcao_instrutor" id="tx_funcao_instrutor" value=""/>
            </div>


            <h5 style="margin-top: 40px">Responsável Técnico</h5>
            <hr style="margin-top: -10px">
            <div align="center">

                <label style="display: inline-block; margin-right: 10px" for="tx_nome_responsavel_tecnico">Nome</label>
                <input class="" style="margin-right: 25px" type="text" name="tx_nome_responsavel_tecnico" id="tx_nome_responsavel_tecnico" value=""/>

                <label class="" style="display: inline-block; margin-right: 10px" for="tx_registro_responsavel_tecnico">Registro</label>
                <input class="input-prepend" style="margin-right: 25px"  type="text" name="tx_registro_responsavel_tecnico" id="tx_registro_responsavel_tecnico" value=""/>

                <label class="" style="display: inline-block; margin-right: 10px" for="tx_funcao_responsavel_tecnico">Função</label>
                <input class="input-prepend" type="text" name="tx_funcao_responsavel_tecnico" id="tx_funcao_responsavel_tecnico" value=""/>

            </div>
            <div class="form-actions">
                <input class="btn btn-primary" id="btEnviar" type="submit" value="Salvar"/>
                <input class="btn" id="btVoltar" onclick="window.back()" type="button" value="Voltar"/>
            </div>
        </fieldset>
    </form>
</div>

<div id="mensagemTreinamento">
    <p style="color: #000 !important"></p>
</div>

<script>
    var dataForm = <?php echo Zend_Json::encode($this->treinamento); ?>;
    
    $(function(){
           
        $('.mce-tinymce .mce-container .mce-panel').each(function(){
            $(this).width(1);
        });
           
        $('#form_treinamento').populate(dataForm);
        
        $('#form_treinamento').validate({
            submitHandler: function(form) {
                tinyMCE.get("tx_descricao").save();
                tinyMCE.get("tx_conteudo_programatico").save();
                jQuery(form).ajaxSubmit({
                    dataType:  'json', 
                    success: function(r){
                        if(r.tipo == 'sucesso'){                    
                            $('#mensagemTreinamento p').html(r.msg);
                            $( "#mensagemTreinamento" ).dialog({
                                modal: true,
                                buttons: {
                                    Ok: function() {
                                        $(this).dialog("close");
                                        window.location = r.url;
                                    }
                                }
                            });
                        } else {
                            $('#mensagemTreinamento p').html(r.msg);
                            $('#mensagemTreinamento').dialog({
                                buttons: {
                                    Ok: function() {
                                        $( this ).dialog( "close" );
                                    }
                                }
                            });
                        }
                    } 
                });
            } 
        });
    });
        
</script>