<table class="table table-bordered table-striped table-hover">
    <tr>
        <th>Nome do Treinamento</th>
        <th>Carga Horária</th>
        <th>Instrutor</th>
        <th>Ações</th>
    </tr>

    <tr class="alt" >
        <?php foreach ($this->paginator as $k => $treinamentos): ?>
        <tr class="<?php echo ($k % 2 == 0) ? 'alt' : '' ?>">
            <td><?php echo $treinamentos['tx_nome_treinamento'] ?></td>
            <td><?php echo $treinamentos['nr_carga_horaria'] ?></td>
            <td><?php echo $treinamentos['tx_nome_instrutor'] ?></td>
            <td>
                <a class="linkEditar" href="<?php echo $this->baseUrl('/admin/treinamento/form') ?>/id/<?php echo $treinamentos['id_treinamento'] ?>">
                    <img src="<?php echo $this->baseUrl('/img/edit-icon.gif') ?>" title="Editar registro" />
                </a>
                <a class="btExcluir" href="<?php echo $this->baseUrl('/admin/treinamento/excluir') ?>/id/<?php echo $treinamentos['id_treinamento'] ?>">
                    <img src="<?php echo $this->baseUrl('/img/delete-icon.gif') ?>" title="Excluir Registro" />
                </a>
            </td>
        </tr>    
    <?php endforeach; ?>

</table>

<?php echo $this->paginationControl($this->paginator, 'Sliding', 'my_pagination_control.phtml'); ?>

<div id="dcTreinamento">
    <span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>Deseja realmente excluir esse treinamento?
</div>

<div id="treinamentoErro">
    Erro    
</div>

<div id="treinamentoSucesso">
    Sucesso    
</div>


<script>
    
    var url = "";
    $(function(){
        
        $( "#treinamentoSucesso" ).dialog({
            modal: true,
            autoOpen: false
        });
        
        $( "#treinamentoErro" ).dialog({
            modal: true,
            autoOpen: false
        });
                
        $("#dcTreinamento").dialog({
            resizable: false,
            height:250,
            width:500,
            modal: true,
            title: "Aviso",
            autoOpen: false,
                
            buttons: {
                "Ok": function() {
                    $.get(url, null, function(retorno){
                        if(retorno.tipo == 'sucesso'){
                            $('#treinamentoSucesso').html(retorno.msg);
                            
                            $('#treinamentoSucesso').dialog({
                                buttons: {
                                    Ok: function() {
                                        $( this ).dialog( "close" );
                                    }
                                }
                            });
                            $('#treinamentoSucesso').dialog("open");    
                            $('#div_treinamento').load('<?php echo $this->baseUrl('admin/treinamento/grid'); ?>');                                
                        } else {
                            $('#treinamentoErro').html(retorno.msg);                            
                            $('#treinamentoErro').dialog({
                                buttons: {
                                    Ok: function() {
                                        $( this ).dialog( "close" );
                                    }
                                }
                            });
                            $('#treinamentoErro').dialog("open");
                            $('#div_treinamento').load('<?php echo $this->baseUrl('admin/treinamento/grid'); ?>');
                        }                    
                    }, 'json');
                    $( this ).dialog("close");
                    
                },
                Cancel: function() {
                    $('#div_treinamento').load('<?php echo $this->baseUrl('/admin/treinamento/grid/') ?>');
                    $( this ).dialog( "close" );
                    
                }
    
            }
                
        });
                
        $('.pagination a').click(function(){
           
            var href = $(this).attr('href');
            $('#div_treinamento').load(href);
            return false;
        });
        
        $('.btExcluir').click(function(){
            
            url = $(this).attr('href');
            $("#dcTreinamento").dialog("open");
            
            return false;
        });
        
    });
    
</script>